package idv.cm;

import java.util.ArrayList;
import java.util.List;

public class UserBean {
	
	private int _id; //generated by database
	private String userName;
	private String userPass;
	private String userNote;
	
	private UserBean(UserBean.Builder build) {
		this._id = build._id;
		this.userName = build.userName;
		this.userPass = build.userPass;
		this.userNote = build.userNote;
	}
	
	public static class Builder{
		private int _id;
		private String userName;
		private String userPass;
		private String userNote;
		
		public UserBean.Builder userId(int val){
			this._id = val;
			return this;
		}
		
		public UserBean.Builder userName(String val){
			this.userName = val;
			return this;
		}
		public UserBean.Builder userPass(String val){
			this.userPass = val;
			return this;
		}
		public UserBean.Builder userNote(String val){
			this.userNote = val;
			return this;
		}
		public UserBean build() {
			return new UserBean(this);
		}
		
	}
	
	

	public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public String getUserNote() {
		return userNote;
	}

	public void setUserNote(String userNote) {
		this.userNote = userNote;
	}
	
	
	
	@Override
	public String toString() {
		return "User [userName=" + userName + ", userPhone=" + userPass + ", userNote=" + userNote + "]";
	}

	public static List<UserBean> createUserList() {
		List<UserBean> list = new ArrayList<>();
		list.add(new UserBean.Builder()
				.userName("Amy")
				.userPass("123456")
				.userNote("Note1")
				.build()
				);
		list.add(new UserBean.Builder()
				.userName("Jackie")
				.userPass("234566")
				.userNote("note2")
				.build()
				);
		list.add(new UserBean.Builder()
				.userName("Lisa")
				.userPass("344567")
				.userNote("note3")
				.build()
				);
		return list;
	}
	
		
}
